Lesson 5
akoltun/reblog-front pull request #5
Opened 2017-01-31 19:23 UTC by akoltun

2017-02-01 09:51 UTC, index01d requested changes
а можно semantic/dist в gitignore добавить? а то очень сложный PR получается.

2017-02-01 10:08 UTC, akoltun commented
Done

2017-02-01 11:58 UTC, index01d requested changes
На будущее просьба после проверки мержить PR в мастер. 

Нужно также удалить dist/bundle.js

Предлагаю также вынести контейнерные компоненты в директорию containers/

Контейнерный компонент BlogPage декомпозировать на контейнеры для Like, PiChart, Pagination, презентационную логику c гридом из этого компонента можно вынести например в `views/BlogPage` или `views/BlogPageView`.

Pagination должен быть отдельным компонентом от BlogList, выводиться под ним. BlogList'у о пейджинации знать незачем.

2017-02-01 11:58 UTC, index01d commented on src/components/widgets/blog/Item.js
> +import { postPath } from 'helpers/routes';
BlogItem лучше передавать уже готовую ссылку, созданную с помощью в postPath в контейнере, тогда презентационный компонент не будет в курсе способа формирования ссылок.

2017-02-01 11:58 UTC, index01d commented on src/components/widgets/blog/Item.js
> +  handleLike() {
не нужно, нужно передавать уже готовую функцию из контейнера

2017-02-02 02:34 UTC, akoltun commented on src/components/widgets/blog/Item.js
> +  handleLike() {
- [x] Ветки привел в порядок
- [x] dist/bundle.js удалил и внес в .gitignore
- [x] Контейнерные компоненты перенес в containers/
- [x] Вынес из BlogList-а отображение пагинатора в Pagination
- [x] BlogPage декомпозировал насколько смог: Вынес логику управления PieChart и пагинацией в отдельные компоненты и сделал работу пагинации через ссылки. Управление поиском и лайками не вынес, посколько они имхо должны управляться из хранилища данных, которое ждет редукса - или я не прав?
- [ ] _не нужно, нужно передавать уже готовую функцию из контейнера_ - так ведь в готовую функцию будет передавать синтетическое событие и компонент, а мне нужно передать  id поста

2017-02-02 02:46 UTC, akoltun commented on src/components/widgets/blog/Item.js
> +  handleLike() {
По-прежнему небольшая путаница с файловой структурой: есть компоненты, (1) которые содержать стэйт (один компонент - BlogPage), (2) презентационные компоненты, отображающие данные на основе props-ов, например BlogList, BlogItem, Pagination и (3) "управляющие" компоненты, которые на основание props-ов готовят данные для презентационных компонентов, например Paginator или PieChart.

Кроме того их можно разделить на универсальные, например Link и Paginator, и на специфичные для Blog-а, например BlogItem, т.е. завязанный на структуру данных поста.

И как их все грамотно размещать, пока не до конца понял.

2017-02-02 02:47 UTC, akoltun commented on src/components/widgets/blog/Item.js
> +  handleLike() {
Компонент Paginator - рендерится non-jsx, потому что не понял как его можно на jsx написать.

2017-02-02 09:40 UTC, akoltun commented
- [x] Ветки привел в порядок
- [x] dist/bundle.js удалил и внес в .gitignore
- [x] Контейнерные компоненты перенес в containers/
- [x] Вынес из BlogList-а отображение пагинатора в Pagination
- [x] BlogPage декомпозировал насколько смог: Вынес логику управления PieChart и пагинацией в отдельные компоненты и сделал работу пагинации через ссылки. Управление поиском и лайками не вынес, посколько они имхо должны управляться из хранилища данных, которое ждет редукса - или я не прав?
- [ ] _не нужно, нужно передавать уже готовую функцию из контейнера_ - так ведь в готовую функцию будет передавать синтетическое событие и компонент, а мне нужно передать  id поста

По-прежнему небольшая путаница с файловой структурой: есть компоненты, (1) которые содержать стэйт (один компонент - BlogPage), (2) презентационные компоненты, отображающие данные на основе props-ов, например BlogList, BlogItem, Pagination и (3) "управляющие" компоненты, которые на основание props-ов готовят данные для презентационных компонентов, например Paginator или PieChart.

Кроме того их можно разделить на универсальные, например Link и Paginator, и на специфичные для Blog-а, например BlogItem, т.е. завязанный на структуру данных поста.

И как их все грамотно размещать, пока не до конца понял.

 Компонент Paginator - рендерится non-jsx, потому что не понял как его можно на jsx написать.

2017-02-04 08:49 UTC, index01d commented
Я немного отписался там на форуме на тему. В данном случае я бы предложил сделать директорию views и держать там представления страниц (унести туда BlogPageView, containers/AboutPage). Возможно путаницу снимет если на данном этапе переименовать BlogPage -> BlogContainer, PostPage -> PostContainer.

То есть общая логика разделения компонентов будет такая
Есть атомные элементы UI (elements), из них состоят сложные виджеты (widgets)

Есть контейнерный компонент, который управляет состоянием.

Роут рисует контейнер, контейнер готовит данные и рисует View. View рисует виджеты или другие контейнеры (эти контейнеры уже могут рисовать другие виджеты, для которых они сготовили состояние).

Route -> Container -> View -> Widgets -> Elements
Route -> Container -> View -> Container -> Widget -> Element

Что касается пейджинации, то все в целом нормально, хотя в начинку пагинатора я пока не полез , если откомментируешь назначение каждого свойства, то я его разберу, но можно и отложить пока. 

В целом это все уже косметика, пока что мы вполне можем продолжить с этим работать и рефакторить по ходу дела

2017-02-04 08:49 UTC, index01d approved these changes

2017-02-04 08:50 UTC, index01d commented
что касается управляющих компонентов, то они совершенно справедливо помещены в widgets

2017-02-13 19:55 UTC, merged