Lesson 6
akoltun/reblog-front pull request #6
Opened 2017-02-13 23:18 UTC by akoltun

2017-02-15 21:00 UTC, index01d commented
извиняюсь за несколько затянувшуюся проверку, но зато я постараюсь дать наиболее подробные комментарии. Не теряйте

2017-02-16 09:44 UTC, index01d requested changes
Очень понравилось наличие реализации состояния загрузки.

По лайкам: если они выделены в отдельный ключ в состоянии для того, чтобы сделать возможность лайкать не только посты, но и другие сущности (например: в будущем комментарии), то лучше выделить под них отдельный reducer. Тогда проще будет решить задачу по унификации обработки лайка. Можно будет сделать action
`like(objectType, objectId)` и вызывать его отовсюду, обрабатывая все одним reducer'ом. И наоборот, если лайкать мы хотим только посты, то надо внести этот ключ обратно в объект item и делать преобразование структуры в reducer'е при получении новых постов/нового поста

В целом все сделано очень неплохо, но я написал несколько рекомендаций по разделению и размещению логики

2017-02-16 09:44 UTC, index01d commented on src/App.js
> +  console.log(arguments);
закрался тут

2017-02-16 09:44 UTC, index01d commented on src/components/containers/SearchContainer.js
> +class SearchContrainer extends React.Component {
Contrainer -> Container

2017-02-16 09:44 UTC, index01d commented on src/components/pages/BlogPage.js
> +            pageCount={Math.ceil(items.length / PAGE_SIZE)}
лучше подсчитать заранее в контейнере, чтобы избежать расчетов в презентационной части

2017-02-16 09:44 UTC, index01d commented on src/components/pages/BlogPage.js
> +            <SearchContainer search={search} onChange={createLink({page})}/>
здесь получилась весьма неочевидная подмена понятий. onChange обычно принимает обработчик события, а в данном случае передается некоторый вспомогательный хелпер, возвращающий значение, который затем используется при обработке.

Имеет смысл вынести метод search в BlogPageContainer. Возможно, при это станет бесполезным SearchContainer (его в этом случае можно удалить). За счет этого иерархия в презентационной части станет проще. 

Может при этом показаться, что BlogPageContainer становится нагруженным. Но мы можем его декомпозировать и в этом случае у нас останется только одна точка входа для всех возможных действий на странице. Таким образом навигация по коду станет проще за счет того, что не придется искать мелкие контейнеры по всему презентационному коду.

2017-02-16 09:44 UTC, index01d commented on src/containers/BlogPageContainer.js
> +const mergeProps = (stateProps, actionProps, ownProps) => {
в данном случае не выглядит необходимой реализация mergeProps, можно все сделать в stateToProps

2017-02-16 09:44 UTC, index01d commented on src/containers/BlogPageContainer.js
> +  const filteredItems = searchStr ? stateProps.items.filter(
Используя lodash-методы filter и method можно написать так
`filter(items, method('title.match', new RegExp(query, 'i')))`

Тогда не нужно будет императивно делать проверки на наличие ключа и приводить все к верхнему регистру

2017-02-16 09:44 UTC, index01d commented on src/containers/BlogPageContainer.js
> +  const filteredItems = searchStr ? stateProps.items.filter(
заодно, все можно будет компактно упихать в stateToProps

2017-02-16 09:44 UTC, index01d commented on src/containers/BlogPageContainer.js
> +  const params = parse(ownProps.location.search.substr(1));
можно кстати для простоты обернуть в helper

2017-02-16 09:44 UTC, index01d commented on src/components/pages/BlogPage.js
> +            createLink={createLink({search})}
вообще говоря лучше, если в презентационных компонентах будет как можно меньше низкоуровневой логики и по иерархии будут передаваться высокоуровневые методы. В данном случае пробрасывается вспомогательный хелпер createLink, в то время как можно было бы сформировать высокоуровневый метод gotoPage

2017-02-16 09:44 UTC, index01d commented on src/components/widgets/BlogList.js
> +          link={postPath(item.id)}
лучше, если item будет приходить из контейнера уже обработанным, с полем содержащим ссылку

2017-02-16 09:44 UTC, index01d commented on src/components/widgets/Posts.js
> +  likes: []
не совсем ясно: почему в данном случае лайки оказались отдельно от постов? в данном случае их вполне можно было оставить внутри item'a как более сложную структуру (преобразуя структуру при обработке новых постов).

2017-02-16 09:44 UTC, index01d commented on src/containers/BlogPageContainer.js
> +  likePost: (id) => dispatch(likePost(id)),
`flowRight(dispatch, likePost)` было бы короче

2017-02-16 09:47 UTC, index01d reviewed
Еще нужно добавить проверку на наличие данных в prepareData в роутах, чтобы каждое нажатие в фильтре не приводило страницу к состоянию загрузки (я писал об этом в ответе на вопрос на форуме). Если бы при этом делался серверный поиск, то лучше было быфильтровать не по каждому нажатию клавиши, а на событие blur

2017-02-17 17:37 UTC, akoltun commented on src/App.js
> +  console.log(arguments);
Done.

А нет ли какого плагина к webpack-у, чтобы он при сборке в продакшн и в тест сам вырезал все console.log-и?

2017-02-17 17:42 UTC, akoltun commented on src/components/containers/SearchContainer.js
> +class SearchContrainer extends React.Component {
Done

2017-02-17 17:43 UTC, akoltun commented on src/components/pages/BlogPage.js
> +            pageCount={Math.ceil(items.length / PAGE_SIZE)}
Done

2017-02-17 18:19 UTC, akoltun commented on src/components/pages/BlogPage.js
> +            createLink={createLink({search})}
Done

Идея была в том, чтобы минимизировать количество передаваемых свойств

2017-02-17 18:21 UTC, akoltun commented on src/components/pages/BlogPage.js
> +            <SearchContainer search={search} onChange={createLink({page})}/>
Done

2017-02-17 18:22 UTC, akoltun commented on src/containers/BlogPageContainer.js
> +  likePost: (id) => dispatch(likePost(id)),
Специально оставил для себя в таком виде, чтобы было наглядно, что происходит

2017-02-17 18:25 UTC, akoltun commented on src/containers/BlogPageContainer.js
> +const mergeProps = (stateProps, actionProps, ownProps) => {
mergeProps используется для того, чтобы получить доступ к ownProps.
А stateToProps, как я понимаю, имеет доступ только к состоянию, но не к свойствам, или я ошибаюсь?

2017-02-17 18:32 UTC, akoltun commented on src/containers/BlogPageContainer.js
> +  const params = parse(ownProps.location.search.substr(1));
Done

2017-02-17 18:49 UTC, akoltun commented on src/containers/BlogPageContainer.js
> +  const filteredItems = searchStr ? stateProps.items.filter(
Честно говоря, не уверен, что это быстрее и короче, но вариант интересный.

А упихать в stateToProps не получится, поскольку нужен доступ к location, который в props-ах, а не в state-е.

2017-02-17 19:44 UTC, akoltun commented on src/components/widgets/BlogList.js
> +          link={postPath(item.id)}
Done.

Согласен, презентационный компонент - совсем не место для этого.
Совсем правильно будет генерировать их на сервере - сервер отдает ресурс вместе с ссылкой на него. 
Но в данном случае мы изучаем реакт, поэтому сделал на клиенте. Однако меня терзают мутные сомнения, я генерирую эту ссылку в stateToProps BlogPageContainer-а, а надо наверное непосредственно при загрузке данных в actions/Posts? Ведь эти ссылки уже не будут меняться, а так в BlogPageContainer я их пересоздаю каждый раз при любом изменении состояния. Верно мыслю?

2017-02-17 21:13 UTC, akoltun commented on src/containers/BlogPageContainer.js
> +const mergeProps = (stateProps, actionProps, ownProps) => {
Done.

Не заметил, что stateToProps тоже получает все props-ы, поэтому реализовал mergeProps

2017-02-18 00:13 UTC, akoltun commented on src/components/widgets/Posts.js
> +  likes: []
Потому что эти likes содержат не count (который внутри item.meta.likes.count), isRequesting и error. Не был уверен, что будет корректно подмешать их в item.

Done.
Перенес likes внутрь item-а

2017-02-18 01:09 UTC, akoltun commented
Проверку добавил, теперь при пажинации и поиске данные с сервера не запрашиваются, если они уже загружены.

2017-02-22 13:05 UTC, index01d approved these changes

2017-03-12 12:45 UTC, merged