Lesson 8
akoltun/reblog-front pull request #8
Opened 2017-03-19 23:09 UTC by akoltun

2017-03-20 22:51 UTC, index01d requested changes
Проблема с расхождением в верстке исчезнет, если в layouts/Header.js на 14 строке в свойстве to компоненту Link передавать не функцию, а результат её выполнения aboutPath -> aboutPath(). Если передавать туда функцию, то она получит параметры действия роутера, которые каждый раз разные и в соответствии с твоим кодом эти параметры будут подставлены в итоговую ссылку. Поэтому получается разный код на сервере и на клиенте. Найти ошибку можно было легко:

В консоль мы получали
```
(client) ;action=POP&amp;key=lpcyxj" data-reactid
(server) ;action=POP&amp;key=7g8pv7" data-reactid
```

Далее следовало открыть view-source (результат серверного рендеринга) и chrome-dev-tools (результат клиентского рендеринга), найти и там и там строчку `;action=POP&amp` (хотя мне кажется ты недокопировал, т.к. мне консоль указала нужный react-id="7" и проще найти точку по нему).

После этого можно сравнить результат и прикинуть почему так могло получиться.

2017-03-20 22:51 UTC, index01d commented on src/components/widgets/PieChart.js
> +const c3 = global.__CLIENT__ ? require('c3') : undefined;
попробуй вместо `global.__CLIENT__` написать просто `__CLIENT__`

2017-03-20 22:51 UTC, index01d commented on src/components/widgets/PieChart.js
> +const c3 = global.__CLIENT__ ? require('c3') : undefined;
ключевое слово global нам здесь не нужно, т.к. это объект из библиотеки node.js и на браузере про него ничего не знают. В конфигурации webpack мы просто устанавливаем значение глоб. переменной  `__CLIENT__`. После установки такой переменной в globals.js через объект global про нее также будет знать и сервер (без необходимости снова указывать global.)

2017-03-21 18:53 UTC, index01d approved these changes
попробуешь сделать дополнительные задания?

2017-03-21 20:23 UTC, akoltun commented
В процессе,

Но это займет какое-то время...

2017-03-27 08:16 UTC, index01d commented
Вместо отключения eslint'a можно в файлах, где используются глобальные переменные, объявить их при помощи комментария
```/* globals __CLIENT__, __SERVER__, ... */```

Насчет c3 вечерком склонирую, запущу и посмотрю в чем дело.

2017-03-27 15:21 UTC, index01d commented
Проблема в том, что c3 пытается смонтироваться раньше, чем будет посчитана геометрия блоков :) Очевидным это становится, если попробовать ресайзить окно после загрузки страницы. В качестве фикса можно задать блоку-контейнеру стиль с шириной `<div style={{ width: '300px' }}>`. Еще один вариант – монтировать график асинхронно (e.g.: на setTimeout).

2017-03-27 15:26 UTC, index01d commented
Тут важно заметить, что проблема разрешится сама собой, когда мы в уроке с production-сборкой отделим стили от основного пакета (с помощью webpack-плагина [ExtractTextPlugin](https://github.com/webpack-contrib/extract-text-webpack-plugin)). Тогда они будут грузиться вперед и c3 не будет испытывать проблем с расчетом геометрии.

2017-03-31 08:17 UTC, index01d approved these changes

2017-04-06 16:24 UTC, merged